name: eqmonitor
description: An earthquake monitoring Application
publish_to: "none"

version: 2.7.0

environment:
  sdk: ^3.5.3
  flutter: ^3.24.3

dependencies:
  adaptive_dialog: ^2.1.0
  app_settings: ^5.1.1
  background_task: ^0.2.0
  collection: ^1.18.0
  crypto: ^3.0.5
  device_info_plus: ^11.0.0
  dio: ^5.7.0
  dynamic_color: ^1.7.0
  envied: ^0.5.4
  eqapi_client:
    path: ../packages/eqapi_client
  eqapi_types:
    path: ../packages/eqapi_types
  extensions:
    path: ../packages/extensions
  feedback: ^3.1.0
  firebase_analytics: ^11.3.3
  firebase_app_installations: ^0.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_email_sender: ^6.0.3
  flutter_hooks: ^0.20.5
  flutter_html: ^3.0.0-alpha.2
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.4
  flutter_secure_storage: ^9.2.2
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^3.0.0-dev.3
  image: ^4.2.0
  in_app_review: ^2.0.9
  intl: ^0.19.0
  jma_code_table_types:
    path: ../packages/jma_code_table_types
  jma_map:
    path: ../packages/jma_map
  jma_parameter_api_client:
    path: ../packages/jma_parameter_api_client
  json_annotation: ^4.9.0
  kyoshin_observation_point_types:
    path: ../packages/kyoshin_observation_point_types
  lat_lng:
    path: ../packages/lat_lng
  latlong2: ^0.9.1
  maplibre_gl: ^0.20.0
  notification_setting_types:
    path: ../packages/notification_setting_types
  ntp: ^2.0.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  purchases_flutter: ^8.1.5
  riverpod_annotation: ^3.0.0-dev.3
  screenshot: 3.0.0
  share_plus: ^10.0.3
  shared_preference_app_group: ^1.1.1
  shared_preferences: ^2.3.2
  sheet:
    git:
      url: https://github.com/YumNumm/modal_bottom_sheet.git
      branch: main
      path: sheet
  shorebird_code_push: ^1.1.3
  soft_edge_blur: ^0.1.3
  synchronized: ^3.2.0
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1
  upgrader: ^11.3.0
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  version: ^3.0.2
  web_socket_client: ^0.1.4
  widgetbook: ^3.8.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  analyzer: ^6.7.0
  build_runner: ^2.4.11
  custom_lint: ^0.5.11
  dependency_validator: ^4.1.0
  envied_generator: ^0.5.4
  flutter_gen_runner: ^5.6.0
  freezed: ^2.5.2
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  pedantic_mono: ^1.27.0
  retrofit_generator: ^9.1.2
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  test: ^1.24.9
  widgetbook_generator: ^3.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/theme/
    - assets/fonts/
    - assets/docs/
    - shorebird.yaml

  shaders:
    - shaders/introduction.frag

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 900
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-ExtraBold.ttf
          weight: 900
