name: Auto Format

# ref: https://qiita.com/blendthink/items/48e6c4b2c0f016da8c72

on:
  workflow_dispatch:
  # 毎週月曜日の日本時間で午前9時に自動実行
  schedule:
    - cron: "0 0 * * 1"

env:
  # フォーマット対象のパス
  FORMAT_PATHS: "."

jobs:
  auto-format:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Add Homebrew to PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Install fvm
        run: |
          brew tap leoafarias/fvm
          brew install fvm

      - name: Setup flutter
        run: fvm install

      - name: Format
        run: fvm flutter format $FORMAT_PATHS

      # 変更が発生した場合は main ブランチに向けてプルリクエストを作成
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: auto format
          title: Auto Format
          body: This was automatically generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          base: main
          branch: auto-format
          branch-suffix: short-commit-hash
