# ワークフロー名を定義(任意の名称)
name: flutter analyze

# トリガーを定義
on:
  # プルリク作成がトリガー(GitHub Actionsが実行される)となる
  pull_request:
    # プルリク作成時とプルリクにコミットが行われた時
    types: [opened, synchronize]
    # 対象ブランチを指定
    branches:
      - develop

  # GitHubページから手動で実行できる
  workflow_dispatch:

# 実行するジョブを定義
jobs:
  # ジョブ名を設定
  flutter_analyze:

    # ジョブを実行する仮想ホストマシンタイプ
    runs-on: ubuntu-latest

    # タイムアウト時間を設定
    timeout-minutes: 5

    # steps配下に実行したいアクションを定義します。(usesもしくはrunを使用することになると思います)
    # uses ・・・ GitHubやサードパーティで用意されているactionを使用できます
    # run ・・・ 実行コマンド
    steps:
      - name: checkout
        uses: actions/checkout@v2

　　　　　　　　　　　　  # flutterインストール（キャッシュする）
      - name: flutter cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.5"
          channel: "stable"
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
 - name: 'Setup flutter environment'
   uses: subosito/flutter-action@v2
   with:
     flutter-version: '2.10.3'
     channel: 'stable'
     cache: true

 - name: 'Cache pubspec dependencies'
   uses: actions/cache@v2
   with:
     path: |
       ${{ env.FLUTTER_HOME }}/.pub-cache
       **/.packages
       **/.flutter-plugins
       **/.flutter-plugin-dependencies
       **/.dart_tool/package_config.json
     key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
     restore-keys: |
       build-pubspec-

 - name: Cache build runner
   uses: actions/cache@v2
   with:
     path: |
       **/.dart_tool/build
     key: build-runner-${{ hashFiles('**/asset_graph.json') }}-${{ hashFiles('**/pubspec.lock') }}
     restore-keys: |
       build-runner-

        # 静的解析の実行
      - name: flutter analyze
        run: flutter analyze
